package Model;

public enum Task {
    KILLPROCESS,
    RESTARTPROCESS,
    FETCHPROCESSES,
    SHUTDOWN,
    RESTART,
    SLEEP,
    ADDUSER,
    EDITUSER,
    DELETEUSER,
    EDITSETTING,
    GETSETTINGS,
    STARTFTP,
    STOPFTP,
    RESTARTFTP,
    CLEANDISK,
    ENABLEWIFI,
    DISABLEWIFI,
    ENABLEBLUETOOTH,
    DISABLEBLUETOOTH,
    LOGIN,
    TESTING
    }
